export const categoryList = [
    {
      id: 1,
      value: 'place',
      label: '🚩 Places',
    },
    {
      id: 2,
      value: 'dish',
      label: '🍕 Dishes',
    },
  ];
  
  export const ratingList = [
    {
      id: 1,
      value: '1',
      label: '1🌟',
    },
    {
      id: 2,
      value: '2',
      label: '2🌟',
    },
    {
      id: 3,
      value: '3',
      label: '3🌟',
    },
    {
      id: 4,
      value: '4',
      label: '4🌟',
    },
    {
      id: 5,
      value: '5',
      label: '5🌟',
    },
  ];
  
  export const dataList = [
    {
      id: 1,
      title: 'lounge resort',
      serviceTime: '45-60min',
      deliveryFee: 3.44,
      category: 'place',
      cuisine: 'american',
      rating: 5,
      price: 2500,
      coverSrc: 'https://images.unsplash.com/photo-1569974498991-d3c12a504f95?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8&w=1000&q=80',
    },
    {
      id: 2,
      title: 'door urban',
      serviceTime: '15-20min',
      deliveryFee: 4.94,
      category: 'place',
      cuisine: 'italian',
      rating: 4,
      price: 1000,
      coverSrc: 'https://www.cyberitalian.com/scripts/WOWslider/data1/images/venezia_by_123rf_iakov_kalinin.jpg',
    },
    {
      id: 3,
      title: 'chow',
      serviceTime: '30-22min',
      deliveryFee: 4.94,
      category: 'place',
      cuisine: 'chinese',
      rating: 3,
      price: 2000,
      coverSrc: 'https://cdn.theculturetrip.com/wp-content/uploads/2019/04/asia-china-chen-768x510.jpg',
    },
    {
      id: 4,
      title: 'wharf seafood',
      serviceTime: '10-18min',
      deliveryFee: 2.14,
      category: 'place',
      cuisine: 'american',
      rating: 1,
      price: 1800,
      coverSrc: 'https://thumbs.dreamstime.com/b/south-american-sea-lions-tierra-del-fuego-13291830.jpg',
    },
    {
      id: 5,
      title: 'Tossin',
      serviceTime: '25-30min',
      deliveryFee: 6.79,
      category: 'place',
      cuisine: 'italian',
      rating: 5,
      price: 2000,
      coverSrc: 'https://www.planetware.com/wpimages/2020/02/italy-in-pictures-beautiful-places-to-photograph-venice-canal.jpg',
    },
    {
      id: 6,
      title: 'stories noodles',
      serviceTime: '5-15min',
      deliveryFee: 2.87,
      category: 'place',
      cuisine: 'chinese',
      rating: 5,
      price: 3500,
      coverSrc: 'https://media.istockphoto.com/photos/the-golden-pavilion-of-absolute-perfection-in-nan-lian-garden-chi-lin-picture-id1294862665?b=1&k=20&m=1294862665&s=170667a&w=0&h=aH5SFkUm3M0-cEYY9w3lklhfjrQrsk-oMPA0NPKFQTw=',
    },
    {
      id: 7,
      title: 'Nacho cheeseburger',
      serviceTime: '50-65min',
      deliveryFee: 8.5,
      category: 'dish',
      cuisine: 'american',
      rating: 2,
      price: 2200,
      coverSrc: 'https://images.squarespace-cdn.com/content/v1/54b2faf2e4b0c67d15add912/1436500220371-AF5ZJDQZF7UB58UZX2ZZ/Grilled+Nacho+Burger',
    },
    {
      id: 8,
      title: 'Mushroom Risotto',
      serviceTime: '10-15min',
      deliveryFee: 1.8,
      category: 'dish',
      cuisine: 'italian',
      rating: 1,
      price: 1900,
      coverSrc: 'https://happybellyfish.com/wp-content/uploads/2020/06/P1290587-min-930x620.jpg',
    },
    {
      id: 9,
      title: 'Shitake Fried Rice',
      serviceTime: '12-18min',
      deliveryFee: 3.33,
      category: 'dish',
      cuisine: 'chinese',
      rating: 4,
      price: 2750,
      coverSrc: 'https://ohsnapletseat.com/wp-content/uploads/2022/04/salmon-fried-rice-4-720x540.jpeg.webp',
    },
    {
      id: 10,
      title: 'Pesto chicken stew',
      serviceTime: '30-38min',
      deliveryFee: 1.9,
      category: 'dish',
      cuisine: 'american',
      rating: 2,
      price: 4350,
      coverSrc: 'https://www.thespruceeats.com/thmb/D1VcOqpxjTmk6e969RCVZlneanU=/1957x1468/smart/filters:no_upscale()/easy-pesto-chicken-roast-22-56a8c0fe3df78cf772a053be.jpg',
    },
    {
      id: 11,
      title: 'Bruschetta',
      serviceTime: '16-20min',
      deliveryFee: 4.1,
      category: 'dish',
      cuisine: 'italian',
      rating: 3,
      price: 3300,
      coverSrc: 'https://easyweeknightrecipes.com/wp-content/uploads/2020/07/Bruschetta-4.jpg',
    },
    {
      id: 12,
      title: 'Dim Sums',
      serviceTime: '24-30min',
      deliveryFee: 1.5,
      category: 'dish',
      cuisine: 'chinese',
      rating: 2,
      price: 4100,
      coverSrc: 'https://cdn.shopify.com/s/files/1/1291/3261/products/9.png?v=1633621386',
    },
  ];